name: Release

on:
  push:
    tags: [ v* ] # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set VERSION
        run: echo '::set-env name=VERSION::'`awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' pom.xml`

      - name: Build with Maven
        run: |
          mvn clean install -DskipTests
          cd target
          tar -zcvf 'java-live-sdk-'$VERSION'.tar.gz' 'java-live-sdk-'$VERSION'.jar'
          cp 'java-live-sdk-'$VERSION'.tar.gz' ../
          tar -zcvf 'java-live-sdk-'$VERSION'-jar-with-dependencies.tar.gz' 'java-live-sdk-'$VERSION'-jar-with-dependencies.jar'
          cp 'java-live-sdk-'$VERSION'-jar-with-dependencies.tar.gz' ../

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Jar
        id: upload-release-java-live-sdk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: './java-live-sdk-'$VERSION'.tar.gz'
          asset_name: 'java-live-sdk-'$VERSION'.tar.gz'
          asset_content_type: application/tar.gz

      - name: Upload Release Asset Jar
        id: upload-release-java-live-sdk-javadoc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: './java-live-sdk-'$VERSION'-jar-with-dependencies.tar.gz'
          asset_name: 'java-live-sdk-'$VERSION'-jar-with-dependencies.tar.gz'
          asset_content_type: application/tar.gz
